name: Build and Test .NET Core Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Run Tests
      run: dotnet test --logger "trx;LogFileName=testresults.xml" --results-directory /github/workspace/TestResults --configuration Release
